repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        name: Code format
        
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Import organization

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Import verification

